# config/packages/ai.yaml
ai:
    agent:
        default:
            platform: 'ai.platform.anthropic'
            model: !php/const Symfony\AI\Platform\Bridge\Anthropic\Claude::HAIKU_3
#            model: '@service(App\Ai\Handler\UserProfileHAndler).getPreferredModel()'
            prompt: |
                You are an AI assistant for a blog management system.
                Always use the tools at your disposal when you need to.
            tools:
                - 'App\Ai\Tool\StatusSearch'
    message_store:
        doctrine:
            dbal:
                messages:
                    connection: default
                    table_name: messages
    chat:
        app_chat:
            agent: 'ai.agent.default'
            message_store: 'ai.message_store.doctrine.dbal.messages'
